/**
 * A model as a mermaid `erDiagram`, and the generated section a README carries
 * it in.
 *
 * This is the module that makes "the diff is the review" true for somebody who
 * does not read YAML. GitHub renders mermaid inside markdown, so a pull request
 * that changes a table shows a changed picture, with nobody installing
 * anything.
 *
 * **The whole risk of this file is that mermaid fails silently.** A table or a
 * column whose name mermaid's ER grammar cannot spell does not produce an error
 * anywhere a person will look: GitHub renders a blank box, in somebody else's
 * pull request, and the author of the model never sees it. Everything below is
 * arranged so that the emitted diagram parses whatever the model contains, and
 * ADR 0023 is the argument. The short version, measured against mermaid 11.17:
 *
 * - **An entity name is always quoted.** `"order-items"` and `"order items"`
 *   and `"style"` all parse; the bare forms of the last two do not, and the
 *   list of bare words the grammar reserves is a list that changes between
 *   mermaid releases. Quoting every name means there is no list to keep in step
 *   with, which is worth more than the quotes cost to read.
 * - **An attribute has no quoted form at all**, in either the type or the name
 *   position, so a name mermaid cannot spell is rewritten to one it can. That
 *   is a change to what the picture says, so where it happens the true
 *   `type name` is emitted as the attribute's comment, which mermaid renders in
 *   its own column beside the rewritten one. Nothing is silently different.
 * - **A relationship label is quoted**, like an entity name, for the same
 *   reason.
 */

import { compareCodeUnits } from '../diagnostics.js'
import type { Column, Model, Table } from '../model/types.js'

/** The first line of the generated section. Everything to `SECTION_END` is ours. */
export const SECTION_BEGIN = '<!-- dbmd:diagram -->'
/** The last line of it. Prose on either side of the pair belongs to whoever wrote it. */
export const SECTION_END = '<!-- /dbmd:diagram -->'

export interface MermaidSection {
  /** The whole generated section, both markers included, newline-terminated. */
  readonly text: string
  /** How many entities the diagram has. */
  readonly tables: number
  /** How many relationship lines it has: one per `ref`. */
  readonly relationships: number
}

/**
 * The model as mermaid's `erDiagram` source, with no fence and no markers.
 *
 * Empty when the model has no tables, because `erDiagram` with nothing under it
 * parses and then renders as an empty box, which is the failure this module is
 * built to avoid producing on purpose.
 */
export function mermaidDiagram(model: Model): string {
  const tables = sortedTables(model)
  if (tables.length === 0) return ''

  const lines = ['erDiagram']
  for (const table of tables) lines.push(...entity(table))
  for (const edge of edges(tables)) lines.push(relationship(edge))
  return `${lines.join('\n')}\n`
}

/**
 * The generated section: the markers, the diagram in a mermaid fence, and the
 * paragraph that says what a diagram of this model is not.
 *
 * The paragraph is here rather than in a doc page because the person it is for
 * is reading the rendered README on GitHub and has no reason to go looking.
 * ADR 0023: a reader who trusts a picture that quietly drops the grouping boxes
 * trusts it more than they should, and one paragraph is cheaper than a layout
 * algorithm and more honest than nothing.
 */
export function mermaidSection(model: Model): MermaidSection {
  const diagram = mermaidDiagram(model)
  const tables = sortedTables(model)
  const body =
    diagram === ''
      ? 'This model has no tables yet, so there is no diagram to draw.\n'
      : `\`\`\`mermaid\n${diagram}\`\`\`\n`

  return {
    text: [SECTION_BEGIN, NOTICE, '', body, CAVEATS, SECTION_END, ''].join('\n'),
    tables: tables.length,
    relationships: edges(tables).length,
  }
}

const NOTICE = `<!-- Generated by "dbmd export". The next export replaces everything between
     these two comments and nothing outside them, so write your own prose above
     or below rather than in here. -->`

const CAVEATS = `The model is the source and this is a picture of one part of it: the tables,
their columns, and the \`ref\` on each column that is a foreign key. \`PK\` is a
primary key, \`FK\` is a \`ref\`, and \`UK\` is a column a single-column \`unique\`
index covers. A dashed line is a \`ref\` that is not part of the child's primary
key.

Everything else in the model is missing from it, because \`erDiagram\` has
nowhere to put it: the sticky notes, the grouping boxes, the canvas layout,
every prose body, the nullability and the default of a column, and every index
except the single-column unique ones above. Mermaid also has no quoting for a
column name or a column type, so one it cannot spell is rewritten, and the real
one is shown beside it in that column's own comment.

Mermaid lays this out itself, and past a few dozen tables it draws a wall
nobody can read. That is what \`dbmd studio\` is for; this is for the pull
request.
`

// --------------------------------------------------------------------------
// Entities.
// --------------------------------------------------------------------------

/**
 * `readModel` already sorts by name in code-unit order, so this is normally a
 * copy. It is here because a `Model` can also be built by hand, by an importer
 * or by a test, and ADR 0006 rule 4 is about the bytes this module emits rather
 * than about where the value came from.
 */
function sortedTables(model: Model): readonly Table[] {
  return [...model.tables].sort((a, b) => compareCodeUnits(a.name, b.name))
}

/** The two things a column can be marked as, gathered once per table. */
interface Keys {
  /** Columns carrying `pk: true`. */
  readonly pk: ReadonlySet<string>
  /** Columns a `unique` index covers on their own, which is the only `unique` a column can wear. */
  readonly unique: ReadonlySet<string>
}

function keysOf(table: Table): Keys {
  const pk = new Set(table.columns.filter((column) => column.pk === true).map((c) => c.name))
  const unique = new Set<string>()
  for (const index of table.indexes) {
    const only = index.columns.length === 1 ? index.columns[0] : undefined
    if (index.unique === true && only !== undefined) unique.add(only)
  }
  return { pk, unique }
}

function entity(table: Table): string[] {
  const keys = keysOf(table)
  return [
    `  ${quoted(table.name)} {`,
    ...table.columns.map((column) => `    ${attribute(column, keys)}`),
    '  }',
  ]
}

/**
 * One column, as `type name [keys] ["the true type and name"]`.
 *
 * Column order is the model's, never sorted: a table's column order is a thing
 * its author chose, which is the case ADR 0006 rule 4 excludes when it says to
 * sort "columns within a table where a sort order is not meaningful".
 */
function attribute(column: Column, keys: Keys): string {
  const type = word(column.type, 'type')
  const name = word(column.name, 'name')

  const markers: string[] = []
  if (keys.pk.has(column.name)) markers.push('PK')
  if (column.ref !== undefined) markers.push('FK')
  if (keys.unique.has(column.name)) markers.push('UK')

  const parts = [type, name]
  if (markers.length > 0) parts.push(markers.join(','))
  // The comment is the only place in an attribute row that can hold arbitrary
  // text, so it is where a rewritten name goes back to being true. It costs a
  // column in the rendered box, and only on the rows that needed it.
  if (type !== column.type || name !== column.name) {
    parts.push(`"${escaped(`${column.type} ${column.name}`)}"`)
  }
  return parts.join(' ')
}

// --------------------------------------------------------------------------
// Relationships. One line per `ref`, which is the only place the format writes
// a foreign key down (ADR 0003).
// --------------------------------------------------------------------------

interface Edge {
  readonly child: Table
  readonly column: Column
  readonly parent: string
  readonly keys: Keys
}

function edges(tables: readonly Table[]): readonly Edge[] {
  const found: Edge[] = []
  for (const child of tables) {
    const keys = keysOf(child)
    for (const column of child.columns) {
      if (column.ref === undefined) continue
      found.push({ child, column, parent: column.ref.table, keys })
    }
  }
  // Grouped by the table being pointed at, so the lines under the entities read
  // as "everything that references customers" rather than as whatever order the
  // columns happen to be in.
  return found.sort(
    (a, b) =>
      compareCodeUnits(a.parent, b.parent) ||
      compareCodeUnits(a.child.name, b.child.name) ||
      compareCodeUnits(a.column.name, b.column.name),
  )
}

/**
 * `"customers" ||--o{ "orders" : "customer_id"`.
 *
 * Read left to right: one customer, zero or more orders. The three parts of the
 * operator are three facts the model already holds, and none of them is
 * guessed.
 *
 * - **Exactly one parent** only when the model says the column is not
 *   nullable, or the column is part of the child's primary key, which cannot be
 *   null. `nullable` absent means the file did not say (ADR 0008), and a
 *   diagram that claims "exactly one" out of silence is claiming something
 *   nobody wrote.
 * - **Zero or one child** when the ref column identifies one child row on its
 *   own: it is the whole primary key, or a single-column unique index covers
 *   it. Otherwise zero or more.
 * - **A solid line** when the ref is part of the child's primary key, which is
 *   the ER convention for an identifying relationship: `order_items` cannot
 *   exist without its order and says so by putting `order_id` in its key.
 */
function relationship(edge: Edge): string {
  const { child, column, keys } = edge
  const inKey = keys.pk.has(column.name)

  const parent = column.nullable === false || inKey ? '||' : '|o'
  const line = inKey ? '--' : '..'
  const one = keys.unique.has(column.name) || (inKey && keys.pk.size === 1)
  const children = one ? 'o|' : 'o{'

  return (
    `  ${quoted(edge.parent)} ${parent}${line}${children} ` +
    `${quoted(child.name)} : ${quoted(column.name)}`
  )
}

// --------------------------------------------------------------------------
// Spelling a name in a way mermaid will accept. The two halves of this section
// are the whole of ADR 0023's "escape or quote", and they are different because
// mermaid's grammar gives the two positions different powers.
// --------------------------------------------------------------------------

/**
 * A name in a position mermaid lets us quote: an entity, or a relationship
 * label. Anything at all can go in one, which is why every such name is quoted
 * rather than only the ones that look dangerous.
 */
function quoted(text: string): string {
  return `"${escaped(text)}"`
}

/**
 * The characters that mean something else inside a mermaid string, as mermaid's
 * own entity escapes.
 *
 * `#` is replaced first, so that the `#` this function writes is not then read
 * as the start of an escape that a table name already contained. A control
 * character becomes a space rather than an escape: it has no legible rendering
 * and a diagram is a thing people look at.
 */
function escaped(text: string): string {
  return text
    .replace(/\p{Cc}/gu, ' ')
    .replace(/#/g, '#35;')
    .replace(/"/g, '#quot;')
    .replace(/</g, '#lt;')
    .replace(/>/g, '#gt;')
}

/**
 * A column type or a column name, as one word mermaid's ER lexer will take.
 *
 * There is no quoted form for either, so this rewrites rather than escapes, and
 * `attribute` puts the true text in the row's comment when it had to. What is
 * allowed through was measured against mermaid 11.17 rather than read off a
 * grammar: a space and a leading digit are what a real column name runs into,
 * and `pk`, `fk` and `uk` are the key markers, which the lexer takes in any
 * case.
 *
 * A comma is allowed in a type and not in a name, because what follows a name
 * is an optional comma-separated list of those key markers, so a comma in a
 * name is ambiguous, while nothing follows a type that a comma could belong to.
 * It is worth the exception: `numeric(10,2)` is what half the columns of a real
 * SQL Server model are typed as.
 */
function word(text: string, position: 'type' | 'name'): string {
  let safe = text.replace(position === 'type' ? UNSAFE_IN_TYPE : UNSAFE_IN_NAME, '_')
  // A leading digit opens a number to the lexer, and an empty word is not a
  // word at all. One underscore answers both.
  if (safe === '' || /^[0-9]/.test(safe)) safe = `_${safe}`
  if (KEY_MARKERS.has(safe.toLowerCase())) safe = `${safe}_`
  return safe
}

/**
 * Everything that is not part of a word, for a name and for a type.
 *
 * A letter is any script's letter rather than `A-Za-z`, because mermaid takes
 * those and rewriting every column of a model written in somebody else's
 * alphabet would be the worst available reading of "escape or quote".
 */
const UNSAFE_IN_NAME = /[^\p{L}\p{N}_\-.\[\]()]/gu
const UNSAFE_IN_TYPE = /[^\p{L}\p{N}_\-.,\[\]()]/gu

/** What mermaid reads as "this column is a key", in any case, so a column called `pk` is not. */
const KEY_MARKERS = new Set(['pk', 'fk', 'uk'])
